{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.gist_flutter_module",
    "module": "flutter_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 14708363,
          "sha512": "75d36d0f59c5352a6a2d90479f888c978dab008a96dd60276607b5f509ac79539451b40bbdfcc59655912bbe6f978f11a1c3ea154d0fab01a777eb69c8817ee1",
          "sha256": "a25030a6aaee1a6ab3e90a2e256d5befa670ad0248625f3deabfbf039071885e",
          "sha1": "6c003a9e8cb3e275c0d68b0e32d29be461638a0a",
          "md5": "4d893ebfa891b22a2b2295c0d5930f40"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-90fa3ae28fe6ddaee1af2c120f01e50201c1401b"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_debug",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.webviewflutter",
          "module": "webview_flutter_android_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 14708363,
          "sha512": "75d36d0f59c5352a6a2d90479f888c978dab008a96dd60276607b5f509ac79539451b40bbdfcc59655912bbe6f978f11a1c3ea154d0fab01a777eb69c8817ee1",
          "sha256": "a25030a6aaee1a6ab3e90a2e256d5befa670ad0248625f3deabfbf039071885e",
          "sha1": "6c003a9e8cb3e275c0d68b0e32d29be461638a0a",
          "md5": "4d893ebfa891b22a2b2295c0d5930f40"
        }
      ]
    }
  ]
}
